#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

clear

# Laravel Pint
echo "\n\n${GREEN} Verifico se sia necessario eseguire Laravel Pint...${NC}"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
if [ -n "$CHANGED_FILES" ]; then
    echo "\n\n${RED} Eseguo Laravel Pint...${NC}"
    composer format $CHANGED_FILES
    git add $CHANGED_FILES
fi
